del D:\stl_files\micro105-bottom-v1.stl
del D:\stl_files\micro105-bottom-v2.stl
del D:\stl_files\micro105-top-v1.stl
del D:\stl_files\micro105-top-v2-cam-down-7.stl
del D:\stl_files\micro105-top-v2-no-cam.stl
del D:\stl_files\micro105-top-v2.stl
del D:\stl_files\hub.stl
del D:\stl_files\hub2.stl
del D:\stl_files\hub2a.stl
del D:\stl_files\hub_mirror.stl
del D:\stl_files\wheel_shape.stl
del D:\stl_files\wheel_shape2.stl
del D:\stl_files\40DP-19T-OD12.17.stl
del D:\stl_files\AT5-8T-OD11.88.stl
del D:\stl_files\GT2_2mm-20T-OD12.22.stl
del D:\stl_files\GT2_3mm-13T-OD11.65.stl
del D:\stl_files\GT2_5mm-8T-OD11.58.stl
del D:\stl_files\H-10T-OD29.55.stl
del D:\stl_files\HTD_3mm-13T-OD11.65.stl
del D:\stl_files\HTD_5mm-9T-OD13.18.stl
del D:\stl_files\HTD_8mm-12T-OD29.18.stl
del D:\stl_files\MXL-20T-OD12.42.stl
del D:\stl_files\T10-10T-OD29.97.stl
del D:\stl_files\T2.5-16T-OD12.20.stl
del D:\stl_files\T5-18T-608-idler.stl
del D:\stl_files\T5-8T-OD11.88.stl
del D:\stl_files\XL-8T-OD12.42.stl
del D:\stl_files\ServoMotor.STL
del D:\stl_files\Bases_Linkage.stl
del D:\stl_files\Base_145x145mm_12holes.stl
del D:\stl_files\Base_17x17cm_12holes.stl
del D:\stl_files\Base_17x17cm_16holes.stl
del D:\stl_files\Base_195x145mm_16holes.stl
del D:\stl_files\Base_19x19cm_12holes.stl
del D:\stl_files\Base_19x19cm_16holes.stl
del D:\stl_files\base_2f.stl
del D:\stl_files\Base_Extension.stl
del D:\stl_files\Base_Joint.stl
del D:\stl_files\Base_Joint_coated.stl
del D:\stl_files\Base_round16cm_12holes.stl
del D:\stl_files\BS_Joint.stl
del D:\stl_files\BS_Joint_2.stl
del D:\stl_files\BS_Joint_coated.stl
del D:\stl_files\BS_Joint_thick_coated.stl
del D:\stl_files\Holder_Alligator.stl
del D:\stl_files\Holder_Hook.stl
del D:\stl_files\Holder_LED.stl
del D:\stl_files\Holder_Magnifying_Glass.stl
del D:\stl_files\Holder_Microclip.stl
del D:\stl_files\Holder_Micrograb.stl
del D:\stl_files\Holder_Sprung.stl
del D:\stl_files\Holder_Tektronix_Probe.stl
del D:\stl_files\Holder_Zeroplus_Probe.stl
del D:\stl_files\PCB_Holder.stl
