ren "D:\stl_files\3d_printer\hub_52 dot 5.stl" "D:\stl_files\3d_printer\hub_52_dot_5.stl"
ren "D:\stl_files\3d_printer\My_Parusa_Clone\Extrusion base.stl" "D:\stl_files\3d_printer\My_Parusa_Clone\Extrusion_base.stl"
ren "D:\stl_files\3d_printer\My_Parusa_Clone\Extrusion bearing base.stl" "D:\stl_files\3d_printer\My_Parusa_Clone\Extrusion_bearing_base.stl"
ren "D:\stl_files\3d_printer\My_Parusa_Clone\Mounting base.stl" "D:\stl_files\3d_printer\My_Parusa_Clone\Mounting_base.stl"
ren "D:\stl_files\3d_printer\My_Parusa_Clone\X motor base.stl" "D:\stl_files\3d_printer\My_Parusa_Clone\X_motor_base.stl"
ren "D:\stl_files\3d_printer\My_Parusa_Clone\X passion base.stl" "D:\stl_files\3d_printer\My_Parusa_Clone\X_passion_base.stl"
ren "D:\stl_files\3d_printer\My_Parusa_Clone\Y belt clip.stl" "D:\stl_files\3d_printer\My_Parusa_Clone\Y_belt_clip.stl"
ren "D:\stl_files\3d_printer\My_Parusa_Clone\Y motor base.stl" "D:\stl_files\3d_printer\My_Parusa_Clone\Y_motor_base.stl"
ren "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt drive 40DP-19T-OD12.17.stl" "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt_drive_40DP-19T-OD12.17.stl"
ren "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt drive AT5-8T-OD11.88.stl" "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt_drive_AT5-8T-OD11.88.stl"
ren "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt drive GT2_2mm-20T-OD12.22.stl" "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt_drive_GT2_2mm-20T-OD12.22.stl"
ren "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt drive GT2_3mm-13T-OD11.65.stl" "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt_drive_GT2_3mm-13T-OD11.65.stl"
ren "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt drive GT2_5mm-8T-OD11.58.stl" "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt_drive_GT2_5mm-8T-OD11.58.stl"
ren "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt drive H-10T-OD29.55.stl" "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt_drive_H-10T-OD29.55.stl"
ren "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt drive HTD_3mm-13T-OD11.65.stl" "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt_drive_HTD_3mm-13T-OD11.65.stl"
ren "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt drive HTD_5mm-9T-OD13.18.stl" "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt_drive_HTD_5mm-9T-OD13.18.stl"
ren "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt drive HTD_8mm-12T-OD29.18.stl" "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt_drive_HTD_8mm-12T-OD29.18.stl"
ren "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt drive MXL-20T-OD12.42.stl" "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt_drive_MXL-20T-OD12.42.stl"
ren "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt drive T10-10T-OD29.97.stl" "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt_drive_T10-10T-OD29.97.stl"
ren "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt drive T2.5-16T-OD12.20.stl" "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt_drive_T2.5-16T-OD12.20.stl"
ren "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt drive T5-18T-608-idler.stl" "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt_drive_T5-18T-608-idler.stl"
ren "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt drive T5-8T-OD11.88.stl" "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt_drive_T5-8T-OD11.88.stl"
ren "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt drive XL-8T-OD12.42.stl" "D:\stl_files\3d_printer\printer_parts\Belt_pulleys\Belt_drive_XL-8T-OD12.42.stl"
ren "D:\stl_files\3d_printer\printer_parts\custom\3d_printer x axis motor mount.stl" "D:\stl_files\3d_printer\printer_parts\custom\3d_printer_x_axis_motor_mount.stl"
ren "D:\stl_files\3d_printer\printer_parts\custom\BUILD PLATE.STL" "D:\stl_files\3d_printer\printer_parts\custom\BUILD_PLATE.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\CHECK GAGES.STL" "D:\stl_files\3d_printer\printer_parts\custom\CHECK_GAGES.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\corner post.STL" "D:\stl_files\3d_printer\printer_parts\custom\corner_post.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\ENGRAVING CLAMP.STL" "D:\stl_files\3d_printer\printer_parts\custom\ENGRAVING_CLAMP.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\EXTRUDER MOUNT BACK.STL" "D:\stl_files\3d_printer\printer_parts\custom\EXTRUDER_MOUNT_BACK.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\EXTRUDER MOUNT FRONT.STL" "D:\stl_files\3d_printer\printer_parts\custom\EXTRUDER_MOUNT_FRONT.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\glass clamp.stl" "D:\stl_files\3d_printer\printer_parts\custom\glass_clamp.stl"
ren "D:\stl_files\3d_printer\printer_parts\custom\glass clamp2.stl" "D:\stl_files\3d_printer\printer_parts\custom\glass_clamp2.stl"
ren "D:\stl_files\3d_printer\printer_parts\custom\hub_52 dot 5.stl" "D:\stl_files\3d_printer\printer_parts\custom\hub_52_dot_5.stl"
ren "D:\stl_files\3d_printer\printer_parts\custom\MELZI COVER.STL" "D:\stl_files\3d_printer\printer_parts\custom\MELZI_COVER.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\MOTOR PIVOT.STL" "D:\stl_files\3d_printer\printer_parts\custom\MOTOR_PIVOT.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\paper HOLDER.STL" "D:\stl_files\3d_printer\printer_parts\custom\paper_HOLDER.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\wire cover.stl" "D:\stl_files\3d_printer\printer_parts\custom\wire_cover.stl"
ren "D:\stl_files\3d_printer\printer_parts\custom\X AXIS SET.STL" "D:\stl_files\3d_printer\printer_parts\custom\X_AXIS_SET.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\X TENSION ARM.STL" "D:\stl_files\3d_printer\printer_parts\custom\X_TENSION_ARM.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\X TENSION END PLATE.STL" "D:\stl_files\3d_printer\printer_parts\custom\X_TENSION_END_PLATE.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\X TENSION SET.STL" "D:\stl_files\3d_printer\printer_parts\custom\X_TENSION_SET.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\X TENSIONER.STL" "D:\stl_files\3d_printer\printer_parts\custom\X_TENSIONER.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\y axis bracket FAR END.STL" "D:\stl_files\3d_printer\printer_parts\custom\y_axis_bracket_FAR_END.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\y axis bracket NEAR END.STL" "D:\stl_files\3d_printer\printer_parts\custom\y_axis_bracket_NEAR_END.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\y axis solid mount ends.STL" "D:\stl_files\3d_printer\printer_parts\custom\y_axis_solid_mount_ends.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\Y BELT BEARING.STL" "D:\stl_files\3d_printer\printer_parts\custom\Y_BELT_BEARING.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\Y BELT MOUNT.STL" "D:\stl_files\3d_printer\printer_parts\custom\Y_BELT_MOUNT.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\y idler.stl" "D:\stl_files\3d_printer\printer_parts\custom\y_idler.stl"
ren "D:\stl_files\3d_printer\printer_parts\custom\y motor adj  bracket.STL" "D:\stl_files\3d_printer\printer_parts\custom\y_motor_adj__bracket.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\y motor adj  pivot.STL" "D:\stl_files\3d_printer\printer_parts\custom\y_motor_adj__pivot.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\y motor adj retainer .STL" "D:\stl_files\3d_printer\printer_parts\custom\y_motor_adj_retainer_.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\z axis bushing .stl" "D:\stl_files\3d_printer\printer_parts\custom\z_axis_bushing_.stl"
ren "D:\stl_files\3d_printer\printer_parts\custom\z stop mount.STL" "D:\stl_files\3d_printer\printer_parts\custom\z_stop_mount.STL"
ren "D:\stl_files\3d_printer\printer_parts\custom\zaxis bushings.stl" "D:\stl_files\3d_printer\printer_parts\custom\zaxis_bushings.stl"
ren "D:\stl_files\downloaded\bushing_8x15x5 (2).stl" "D:\stl_files\downloaded\bushing_8x15x5_(2).stl"
ren "D:\stl_files\downloaded\Screw Holder Bottom.stl" "D:\stl_files\downloaded\Screw_Holder_Bottom.stl"
ren "D:\stl_files\downloaded\cat\bucket linkage.stl" "D:\stl_files\downloaded\cat\bucket_linkage.stl"
ren "D:\stl_files\downloaded\cat\TrkMdlPart_horizontal .stl" "D:\stl_files\downloaded\cat\TrkMdlPart_horizontal_.stl"
ren "D:\stl_files\downloaded\solder_station\Extension Linkage Base17x17-12h.stl" "D:\stl_files\downloaded\solder_station\Extension_Linkage_Base17x17-12h.stl"
ren "D:\stl_files\downloaded\solder_station\Extension Linkage Base17x17-16h.stl" "D:\stl_files\downloaded\solder_station\Extension_Linkage_Base17x17-16h.stl"
ren "D:\stl_files\downloaded\solder_station\Extension Linkage Base19x19-12h.stl" "D:\stl_files\downloaded\solder_station\Extension_Linkage_Base19x19-12h.stl"
ren "D:\stl_files\downloaded\solder_station\Extension Linkage Base19x19-16h.stl" "D:\stl_files\downloaded\solder_station\Extension_Linkage_Base19x19-16h.stl"
ren "D:\stl_files\downloaded\solder_station\Extension Linkage Side145mm.stl" "D:\stl_files\downloaded\solder_station\Extension_Linkage_Side145mm.stl"
ren "D:\stl_files\downloaded\solder_station\Extension Linkage Side195mm.stl" "D:\stl_files\downloaded\solder_station\Extension_Linkage_Side195mm.stl"
ren "D:\stl_files\hardware_store\3 DRAWER BOX RISERS.STL" "D:\stl_files\hardware_store\3_DRAWER_BOX_RISERS.STL"
ren "D:\stl_files\hardware_store\electrical\ARDUINO TOP.STL" "D:\stl_files\hardware_store\electrical\ARDUINO_TOP.STL"
ren "D:\stl_files\hardware_store\electrical\ELEC BOX.STL" "D:\stl_files\hardware_store\electrical\ELEC_BOX.STL"
ren "D:\stl_files\hardware_store\electrical\TWO GANG BOX COVER.STL" "D:\stl_files\hardware_store\electrical\TWO_GANG_BOX_COVER.STL"
ren "D:\stl_files\hardware_store\electrical\TWO GANG BOX.STL" "D:\stl_files\hardware_store\electrical\TWO_GANG_BOX.STL"
ren "D:\stl_files\hardware_store\electrical\battery\BATTERY BOX.STL" "D:\stl_files\hardware_store\electrical\battery\BATTERY_BOX.STL"
ren "D:\stl_files\hardware_store\electrical\battery\BATTERY RACK 1.STL" "D:\stl_files\hardware_store\electrical\battery\BATTERY_RACK_1.STL"
ren "D:\stl_files\hardware_store\electrical\battery\BATTERY RACK 2.STL" "D:\stl_files\hardware_store\electrical\battery\BATTERY_RACK_2.STL"
ren "D:\stl_files\hardware_store\electrical\battery\BATTERY RACK 3.STL" "D:\stl_files\hardware_store\electrical\battery\BATTERY_RACK_3.STL"
ren "D:\stl_files\hardware_store\electrical\battery\BATTERY SPACER.STL" "D:\stl_files\hardware_store\electrical\battery\BATTERY_SPACER.STL"
ren "D:\stl_files\hardware_store\electrical\battery\NEW CHARGER.STL" "D:\stl_files\hardware_store\electrical\battery\NEW_CHARGER.STL"
ren "D:\stl_files\hardware_store\electrical\battery\NEW CHARGER2.STL" "D:\stl_files\hardware_store\electrical\battery\NEW_CHARGER2.STL"
ren "D:\stl_files\hardware_store\electrical\battery\NEW CHARGER3.STL" "D:\stl_files\hardware_store\electrical\battery\NEW_CHARGER3.STL"
ren "D:\stl_files\hardware_store\electrical\battery\recharge double base.STL" "D:\stl_files\hardware_store\electrical\battery\recharge_double_base.STL"
ren "D:\stl_files\hardware_store\electrical\bedini\wall and foot.stl" "D:\stl_files\hardware_store\electrical\bedini\wall_and_foot.stl"
ren "D:\stl_files\hardware_store\electrical\bedini\wall and foot2.stl" "D:\stl_files\hardware_store\electrical\bedini\wall_and_foot2.stl"
ren "D:\stl_files\hardware_store\tooling\30X45 TRIANGLE.STL" "D:\stl_files\hardware_store\tooling\30X45_TRIANGLE.STL"
ren "D:\stl_files\hardware_store\tooling\45 angle guide.STL" "D:\stl_files\hardware_store\tooling\45_angle_guide.STL"
ren "D:\stl_files\hardware_store\tooling\AXE WEDGE.STL" "D:\stl_files\hardware_store\tooling\AXE_WEDGE.STL"
ren "D:\stl_files\hardware_store\tooling\DRILL JIG.STL" "D:\stl_files\hardware_store\tooling\DRILL_JIG.STL"
ren "D:\stl_files\hardware_store\tooling\expanding wedge.STL" "D:\stl_files\hardware_store\tooling\expanding_wedge.STL"
ren "D:\stl_files\hardware_store\tooling\MITRE FENCE.STL" "D:\stl_files\hardware_store\tooling\MITRE_FENCE.STL"
ren "D:\stl_files\hardware_store\tooling\paint ROLLER.STL" "D:\stl_files\hardware_store\tooling\paint_ROLLER.STL"
ren "D:\stl_files\hardware_store\tooling\paint ROLLER2.STL" "D:\stl_files\hardware_store\tooling\paint_ROLLER2.STL"
ren "D:\stl_files\hardware_store\tooling\paint ROLLER3.STL" "D:\stl_files\hardware_store\tooling\paint_ROLLER3.STL"
ren "D:\stl_files\hardware_store\tooling\TABLET BASE.STL" "D:\stl_files\hardware_store\tooling\TABLET_BASE.STL"
ren "D:\stl_files\hardware_store\tooling\gears\18t_DRIVE GEAR.STL" "D:\stl_files\hardware_store\tooling\gears\18t_DRIVE_GEAR.STL"
ren "D:\stl_files\hardware_store\tooling\gears\40x14_IDLE GEAR.STL" "D:\stl_files\hardware_store\tooling\gears\40x14_IDLE_GEAR.STL"
ren "D:\stl_files\hardware_store\tooling\gears\48t_MAIN GEAR.STL" "D:\stl_files\hardware_store\tooling\gears\48t_MAIN_GEAR.STL"
ren "D:\stl_files\hardware_store\tooling\hd\TANK RING.STL" "D:\stl_files\hardware_store\tooling\hd\TANK_RING.STL"
ren "D:\stl_files\hardware_store\tooling\hd\TANK SANDER.STL" "D:\stl_files\hardware_store\tooling\hd\TANK_SANDER.STL"
ren "D:\stl_files\hardware_store\tooling\hd\TANK SANDER2.STL" "D:\stl_files\hardware_store\tooling\hd\TANK_SANDER2.STL"
ren "D:\stl_files\hardware_store\tooling\hd\TANKSAVER 1.STL" "D:\stl_files\hardware_store\tooling\hd\TANKSAVER_1.STL"
ren "D:\stl_files\hardware_store\tooling\hd\TANKSAVER 2.STL" "D:\stl_files\hardware_store\tooling\hd\TANKSAVER_2.STL"
ren "D:\stl_files\hardware_store\tooling\hd\TANKSAVER 3.STL" "D:\stl_files\hardware_store\tooling\hd\TANKSAVER_3.STL"
ren "D:\stl_files\hardware_store\tooling\hd\TANKSAVER 4.STL" "D:\stl_files\hardware_store\tooling\hd\TANKSAVER_4.STL"
ren "D:\stl_files\hardware_store\tooling\hd\TANKSAVER 5.STL" "D:\stl_files\hardware_store\tooling\hd\TANKSAVER_5.STL"
ren "D:\stl_files\hardware_store\tooling\hd\TANKSAVER FILING JIG.STL" "D:\stl_files\hardware_store\tooling\hd\TANKSAVER_FILING_JIG.STL"
ren "D:\stl_files\misc\camera_mount\CAMERA MOUNT.STL" "D:\stl_files\misc\camera_mount\CAMERA_MOUNT.STL"
ren "D:\stl_files\misc\camera_mount\CAMERA MOUNT2.STL" "D:\stl_files\misc\camera_mount\CAMERA_MOUNT2.STL"
ren "D:\stl_files\misc\camera_mount\CAMERA MOUNT3.STL" "D:\stl_files\misc\camera_mount\CAMERA_MOUNT3.STL"
ren "D:\stl_files\misc\sight\LASER SIGHT BODY.STL" "D:\stl_files\misc\sight\LASER_SIGHT_BODY.STL"
ren "D:\stl_files\misc\sight\LASER SIGHT SLIDER POSITION.STL" "D:\stl_files\misc\sight\LASER_SIGHT_SLIDER_POSITION.STL"
ren "D:\stl_files\misc\sight\LASER SIGHT SLIDER PRINT.STL" "D:\stl_files\misc\sight\LASER_SIGHT_SLIDER_PRINT.STL"
ren "D:\stl_files\misc\sight\LASER SIGHT SWITCH.STL" "D:\stl_files\misc\sight\LASER_SIGHT_SWITCH.STL"
ren "D:\stl_files\toolchanger\transfer_claw\3d_printer x axis motor mount.stl" "D:\stl_files\toolchanger\transfer_claw\3d_printer_x_axis_motor_mount.stl"
ren "D:\stl_files\toolchanger\transfer_claw\ARM SUPPORT.STL" "D:\stl_files\toolchanger\transfer_claw\ARM_SUPPORT.STL"
ren "D:\stl_files\toolchanger\transfer_claw\bracket arm.stl" "D:\stl_files\toolchanger\transfer_claw\bracket_arm.stl"
ren "D:\stl_files\toolchanger\transfer_claw\FIRST ARM.STL" "D:\stl_files\toolchanger\transfer_claw\FIRST_ARM.STL"
ren "D:\stl_files\toolchanger\transfer_claw\JAW ARM.STL" "D:\stl_files\toolchanger\transfer_claw\JAW_ARM.STL"
ren "D:\stl_files\toolchanger\transfer_claw\LEFT JAW.STL" "D:\stl_files\toolchanger\transfer_claw\LEFT_JAW.STL"
ren "D:\stl_files\toolchanger\transfer_claw\NEW ARM.STL" "D:\stl_files\toolchanger\transfer_claw\NEW_ARM.STL"
ren "D:\stl_files\toolchanger\transfer_claw\NEW ARM2.STL" "D:\stl_files\toolchanger\transfer_claw\NEW_ARM2.STL"
ren "D:\stl_files\toolchanger\transfer_claw\OTHER ARM.STL" "D:\stl_files\toolchanger\transfer_claw\OTHER_ARM.STL"
ren "D:\stl_files\toolchanger\transfer_claw\PARUSA ROBOTIC ARM.STL" "D:\stl_files\toolchanger\transfer_claw\PARUSA_ROBOTIC_ARM.STL"
ren "D:\stl_files\toolchanger\transfer_claw\RIGHT JAW.STL" "D:\stl_files\toolchanger\transfer_claw\RIGHT_JAW.STL"
ren "D:\stl_files\toolchanger\transfer_claw\SECOND ARM.STL" "D:\stl_files\toolchanger\transfer_claw\SECOND_ARM.STL"
ren "D:\stl_files\toolchanger\version_2\18t_DRIVE GEAR.STL" "D:\stl_files\toolchanger\version_2\18t_DRIVE_GEAR.STL"
ren "D:\stl_files\toolchanger\version_2\40x14_IDLE GEAR.STL" "D:\stl_files\toolchanger\version_2\40x14_IDLE_GEAR.STL"
ren "D:\stl_files\toolchanger\version_2\48t_MAIN GEAR.STL" "D:\stl_files\toolchanger\version_2\48t_MAIN_GEAR.STL"
ren "D:\stl_files\toolchanger\version_2\ACTUATOR ARM.STL" "D:\stl_files\toolchanger\version_2\ACTUATOR_ARM.STL"
ren "D:\stl_files\toolchanger\version_2\ACTUATOR LINK.STL" "D:\stl_files\toolchanger\version_2\ACTUATOR_LINK.STL"
ren "D:\stl_files\toolchanger\version_2\ACTUATOR ROD RETAINER.STL" "D:\stl_files\toolchanger\version_2\ACTUATOR_ROD_RETAINER.STL"
ren "D:\stl_files\toolchanger\version_2\BEARING ARM.STL" "D:\stl_files\toolchanger\version_2\BEARING_ARM.STL"
ren "D:\stl_files\toolchanger\version_2\BLOCK LEFT.STL" "D:\stl_files\toolchanger\version_2\BLOCK_LEFT.STL"
ren "D:\stl_files\toolchanger\version_2\BLOCK MOLD 3.STL" "D:\stl_files\toolchanger\version_2\BLOCK_MOLD_3.STL"
ren "D:\stl_files\toolchanger\version_2\BLOCK MOLD LEFT.STL" "D:\stl_files\toolchanger\version_2\BLOCK_MOLD_LEFT.STL"
ren "D:\stl_files\toolchanger\version_2\BLOCK MOLD RIGHT.STL" "D:\stl_files\toolchanger\version_2\BLOCK_MOLD_RIGHT.STL"
ren "D:\stl_files\toolchanger\version_2\BLOCK RIGHT.STL" "D:\stl_files\toolchanger\version_2\BLOCK_RIGHT.STL"
ren "D:\stl_files\toolchanger\version_2\FEED DOG.STL" "D:\stl_files\toolchanger\version_2\FEED_DOG.STL"
ren "D:\stl_files\toolchanger\version_2\MOUNTING BRACKET.STL" "D:\stl_files\toolchanger\version_2\MOUNTING_BRACKET.STL"
ren "D:\stl_files\toolchanger\version_2\PIVOT GEAR 24.STL" "D:\stl_files\toolchanger\version_2\PIVOT_GEAR_24.STL"
ren "D:\stl_files\toolchanger\version_2\platter (2).stl" "D:\stl_files\toolchanger\version_2\platter_(2).stl"
ren "D:\stl_files\toolchanger\version_2\ROTATION BLOCK.STL" "D:\stl_files\toolchanger\version_2\ROTATION_BLOCK.STL"
ren "D:\stl_files\toolchanger\version_2\SERVO ARM BUSHING.STL" "D:\stl_files\toolchanger\version_2\SERVO_ARM_BUSHING.STL"
ren "D:\stl_files\toolchanger\version_2\SERVO ARM.STL" "D:\stl_files\toolchanger\version_2\SERVO_ARM.STL"
ren "D:\stl_files\toolchanger\version_2\SERVO HORN.STL" "D:\stl_files\toolchanger\version_2\SERVO_HORN.STL"
ren "D:\stl_files\toolchanger\version_2\SPRING RETAINER.STL" "D:\stl_files\toolchanger\version_2\SPRING_RETAINER.STL"
ren "D:\stl_files\toolchanger\version_2\STATIONARY GEAR 48.STL" "D:\stl_files\toolchanger\version_2\STATIONARY_GEAR_48.STL"
ren "D:\stl_files\toolchanger\version_2\SUPPORT PLATE.STL" "D:\stl_files\toolchanger\version_2\SUPPORT_PLATE.STL"
ren "D:\stl_files\toolchanger\version_2\TOP PLATE.STL" "D:\stl_files\toolchanger\version_2\TOP_PLATE.STL"
ren "D:\stl_files\toolchanger\version_2\TRANSFER PLATE.STL" "D:\stl_files\toolchanger\version_2\TRANSFER_PLATE.STL"
ren "D:\stl_files\toolchanger\version_2\extra\10MM MAGNET.STL" "D:\stl_files\toolchanger\version_2\extra\10MM_MAGNET.STL"
ren "D:\stl_files\toolchanger\version_2\extra\ACTUATOR ROD.STL" "D:\stl_files\toolchanger\version_2\extra\ACTUATOR_ROD.STL"
ren "D:\stl_files\toolchanger\version_2\extra\ATTACHMENT BRACKET.STL" "D:\stl_files\toolchanger\version_2\extra\ATTACHMENT_BRACKET.STL"
ren "D:\stl_files\toolchanger\version_2\extra\BLOCK MOLD 3.STL" "D:\stl_files\toolchanger\version_2\extra\BLOCK_MOLD_3.STL"
ren "D:\stl_files\toolchanger\version_2\extra\BLOCK MOLD LEFT.STL" "D:\stl_files\toolchanger\version_2\extra\BLOCK_MOLD_LEFT.STL"
ren "D:\stl_files\toolchanger\version_2\extra\BLOCK MOLD RIGHT.STL" "D:\stl_files\toolchanger\version_2\extra\BLOCK_MOLD_RIGHT.STL"
ren "D:\stl_files\toolchanger\version_2\extra\DRILL JIG.STL" "D:\stl_files\toolchanger\version_2\extra\DRILL_JIG.STL"
ren "D:\stl_files\toolchanger\version_2\extra\FEED BEARING.STL" "D:\stl_files\toolchanger\version_2\extra\FEED_BEARING.STL"
ren "D:\stl_files\toolchanger\version_2\extra\FEED DOG.STL" "D:\stl_files\toolchanger\version_2\extra\FEED_DOG.STL"
ren "D:\stl_files\toolchanger\version_2\extra\FRONT HEATER SPACER.STL" "D:\stl_files\toolchanger\version_2\extra\FRONT_HEATER_SPACER.STL"
ren "D:\stl_files\toolchanger\version_2\extra\GUIDE PIN.STL" "D:\stl_files\toolchanger\version_2\extra\GUIDE_PIN.STL"
ren "D:\stl_files\toolchanger\version_2\extra\HEATER BLOCK.STL" "D:\stl_files\toolchanger\version_2\extra\HEATER_BLOCK.STL"
ren "D:\stl_files\toolchanger\version_2\extra\HEATER PLATE.STL" "D:\stl_files\toolchanger\version_2\extra\HEATER_PLATE.STL"
ren "D:\stl_files\toolchanger\version_2\extra\HEATER STOP.STL" "D:\stl_files\toolchanger\version_2\extra\HEATER_STOP.STL"
ren "D:\stl_files\toolchanger\version_2\extra\M6 NUT.STL" "D:\stl_files\toolchanger\version_2\extra\M6_NUT.STL"
ren "D:\stl_files\toolchanger\version_2\extra\MOLD SET.STL" "D:\stl_files\toolchanger\version_2\extra\MOLD_SET.STL"
ren "D:\stl_files\toolchanger\version_2\extra\NOZZLE BLOCK.STL" "D:\stl_files\toolchanger\version_2\extra\NOZZLE_BLOCK.STL"
ren "D:\stl_files\toolchanger\version_2\extra\NOZZLE STEM.STL" "D:\stl_files\toolchanger\version_2\extra\NOZZLE_STEM.STL"
ren "D:\stl_files\toolchanger\version_2\extra\REAR HEATER SPACER.STL" "D:\stl_files\toolchanger\version_2\extra\REAR_HEATER_SPACER.STL"
ren "D:\stl_files\toolchanger\version_2\extra\STEPPER MOTOR.STL" "D:\stl_files\toolchanger\version_2\extra\STEPPER_MOTOR.STL"
ren "D:\stl_files\toolchanger\version_2\extra\TRANSFER BLOCK.STL" "D:\stl_files\toolchanger\version_2\extra\TRANSFER_BLOCK.STL"
