10MM MAGNET.STL
ACTUATOR ROD.STL
ATTACHMENT BRACKET.STL
BLOCK MOLD 3.STL
BLOCK MOLD LEFT.STL
BLOCK MOLD RIGHT.STL
DRILL JIG.STL
FEED BEARING.STL
FEED DOG.STL
FRONT HEATER SPACER.STL
GUIDE PIN.STL
HEATER BLOCK.STL
HEATER PLATE.STL
HEATER STOP.STL
M6 NUT.STL
MOLD SET.STL
NOZZLE BLOCK.STL
NOZZLE STEM.STL
NOZZLE.STL
REAR HEATER SPACER.STL
SERVO.STL
STEPPER MOTOR.STL
TEMPLATES.STL
TRANSFER BLOCK.STL
